services:
  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: proyecto-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: proyecto_clinico
      MYSQL_USER: proyecto_user
      MYSQL_PASSWORD: proyecto_pass
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

  # Backend FastAPI
  backend:
    build: ./backend
    container_name: proyecto-backend
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_USER: proyecto_user
      MYSQL_PASSWORD: proyecto_pass
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: proyecto_clinico
      DATABASE_URL: "mysql+mysqlconnector://proyecto_user:proyecto_pass@db:3306/proyecto_clinico"
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: >
      sh -c "python wait_for_db.py && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/app

  # Frontend Angular (NGINX producci√≥n)
  frontend:
    build:
      context: ./panel-doctor
      dockerfile: Dockerfile
    container_name: proyecto-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"   
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: